# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  guzzleclient.class: GuzzleHttp\Client
  apirequest.class: YoutubeBundle\Util\APIRequest
  email.class: YoutubeBundle\Util\Email
  swiftmailercustom.class: Swift_Message

services:
    guzzleclient:
        class: "%guzzleclient.class%"
    apirequest:
        class: "%apirequest.class%"
        arguments: ["@guzzleclient"]
    emailmessage:
        class: EmailmessageFactory
        factory: ["%swiftmailercustom.class%", newInstance]
    emailsender:
        class: "%email.class%"
        arguments: ["@mailer", "@emailmessage"]